In [39]:
import numpy as np

In [40]:
def evaluate(A, Y, w):
    Yhat = np.argmax(A.dot(w), axis=1)
    print('Y_hat = ', Yhat)
    print('Y_train = ', Y)
    return np.sum(Yhat == Y) / Y.shape[0]

In [41]:
# load data
with np.load('data/fer2013_train.npz') as data:
    X_train, Y_train = data['X'], data['Y']

with np.load('data/fer2013_test.npz') as data:
    X_test, Y_test = data['X'], data['Y']

In [42]:
print(X_train)

[[ 24  32  36 ... 142 143 142]
 [ 20  17  19 ...  99 107 118]
 [ 77  78  79 ... 125  67  68]
 ...
 [190 222 233 ... 174 175 175]
 [ 88  83  82 ... 194 191 175]
 [254 247 208 ... 254 253 254]]


In [43]:
# one-hot labels
I = np.eye(3)
Y_oh_train, Y_oh_test = I[Y_train], I[Y_test]

In [44]:
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [71]:
d = 500
W = np.random.normal(size=(X_train.shape[1], d))
# select first 100 dimensions
A_train, A_test = X_train.dot(W), X_test.dot(W)

In [72]:
# train model
w = np.linalg.inv(A_train.T.dot(A_train)).dot(A_train.T.dot(Y_oh_train))

In [73]:
# evaluate model
ols_train_accuracy = evaluate(A_train, Y_train, w)
print('(ols) Train Accuracy:', ols_train_accuracy)
ols_test_accuracy = evaluate(A_test, Y_test, w)
print('(ols) Test Accuracy:', ols_test_accuracy)

Y_hat =  [0 0 0 ... 2 0 2]
Y_train =  [1 1 0 ... 2 1 2]
(ols) Train Accuracy: 0.6425199947554739
Y_hat =  [0 1 0 ... 0 0 1]
Y_train =  [1 1 0 ... 0 0 0]
(ols) Test Accuracy: 0.6157880933648047
